version: '2.1'
services:
  db:
    image: postgres:9.4
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: apirest
  websocket:
    build: ./websocket/
    ports:
      - "8025:8025"
    links:
      - db:database
    depends_on:
      db:
        condition: service_started
  server:
    build: ./server/
    ports:
      - "8080:8080"
    links:
      - db:database
    depends_on:
      db:
        condition: service_started
