version: '2.1'
services:
  db:
    image: postgres:9.6.1
    environment:
      - POSTGRES_USER:'root'
      - POSTGRES_PASSWORD:'root'
      - POSTGRES_DB:'apirest'
  server:
    build: ./server/
    ports:
      - "8080:8080"
    links:
      - db:database
    depends_on:
      db:
        condition: service_started
    command: mvn exec:java
  #client:
  #  build: ./web/
  #  volumes:
  #    - ./web/dist:/home/app
  #  links:
  #    - server:server
  #  depends_on:
  #    server:
  #      condition: service_started
